services:
  pialert:
    container_name: pialert
    image: "jokobsk/pi.alert:latest"      
    restart: unless-stopped
    ports:
      - 20211:80
    volumes:
      - pialert_db:/home/pi/pialert/db
      - pialert_config:/home/pi/pialert/config
    environment:
      - TZ=America/Sao_Paulo
    networks:
      - docker_default
volumes:
  pialert_db:
  pialert_config:
networks:
  docker_default:
    external: true