version: '3.8'
services:
  ansible:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ansible:/ansible
    environment:
      ANSIBLE_HOST_KEY_CHECKING: 'False'
    networks:
        - docker_default
volumes:
    ansible:
networks:
    docker_default: