services:
  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: always
    ports:
      - 3020:3000
    environment:
      - TZ=America/Sao_Paulo    
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_BASIC_ENABLED=false
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - docker_default
volumes:
  grafana_data:
networks:
  docker_default:
    external: true