services:
  dashy:
    image: lissy93/dashy
    container_name: Dashy
    volumes:
      - dashy_config:/app/public/conf.yml
    ports:
      - 4000:80
    environment:
      - NODE_ENV=production
    # Specify your user ID and group ID. You can find this by running `id -u` and `id -g`
    #  - UID=1000
    #  - GID=1000
    restart: unless-stopped
    healthcheck:
      test: ['CMD', 'node', '/app/services/healthcheck']
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - docker_default
volumes:
  dashy_config:
networks:
  docker_default:
    external: true