services:
  nextcloud:
    image: lscr.io/linuxserver/nextcloud
    container_name: nextcloud
    environment:
      - PUID=1000
      - PGID=100
      - TZ=America/Sao_Paulo
    volumes:
      - nextcloud_config:/config
      - nextcloud_data:/data
    ports:
      - 444:443
    restart: unless-stopped
    networks:
      - docker_default
volumes:
  nextcloud_config:
  nextcloud_data:
networks:
  docker_default:
    external: true