services:
  adguardhome:
      container_name: adguardhome
      restart: unless-stopped
      networks:
        - docker_default
      volumes:
        - workdir:/opt/adguardhome/work
        - confdir:/opt/adguardhome/conf
      ports:
        - 53:53/tcp
        - 53:53/udp
        - 67:67/udp
        - 68:68/udp
        - 80:80/tcp
        - 443:443/tcp
        - 443:443/udp
        - 3111:3000/tcp
        - 853:853/tcp
        - 853:853/udp
        - 5443:5443/tcp
        - 5443:5443/udp
        - 6060:6060/tcp
      image: adguard/adguardhome

networks:
  docker_default:
    external: true
volumes:
  workdir:
  confdir:
