version: '3.8'
services:
  openvpn:
    image: kylemanna/openvpn
    container_name: openvpn-server
    volumes:
      - data:/etc/openvpn
    ports:
      - "1194:1194/udp"
    cap_add:
      - NET_ADMIN
    environment:
      - OPENVPN_URL=udp://VPN.SERVERNAME.COM
    restart: always
    networks:
      - docker_default
volumes:
  data:
networks:
  docker_default:
    external: true