services:
  glances:
    container_name: glances
    image: joweisberg/glances:latest
    restart: unless-stopped
    pid: host
    ports:
      - 61208:61208
    environment:
      - TZ=America/Sao_Paulo 
      - GLANCES_OPT=--webserver
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - glances_data:/glances/conf
    networks:
      - docker_default
volumes:
  glances_data:
networks:
  docker_default:
    external: true