services:
  homarr:
    image: ghcr.io/ajnart/homarr:latest
    container_name: homarr
    restart: unless-stopped
    ports:
      - "7575:7575"
    volumes:
      - homarr_data:/config
    networks:
      - docker_default

networks:
  docker_default:
    external: true

volumes:
  homarr_data: